language: python
python:
   - 2.7
   - 3.4
install:
   #  APT stuff is below separately
   # 
   # 1. at some point, move all this to requirements.txt; see http://docs.travis-ci.com/user/languages/python/
   # 2. pip is exported for active virtualenv (2.7 or 3.4), no need to change anything :)
   # 3. numpy is pre-installed by travis implicitly
   - pip install pyro4 future nose rednose
   - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pyvtk; fi
   - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip3 install git+https://code.google.com/r/fghorow-pyvtk-python3-port/; fi
   # install mupif itself
   - python setup.py install 

#before_script:
#   # see https://github.com/fabric/fabric/blob/master/.travis.yml
#   # for allowing passwordless SSH to localhost
script:
   - ls -l
   - pwd
   - pushd mupif/examples
   - /bin/bash testExamples.sh
   - popd
   - nosetests --rednose -v
##
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
##
sudo: false
## maybe install NumPy from miniconda in the future: https://gist.github.com/dan-blanchard/7045057
addons:
   apt:
      packages:
         - libblas-dev
         - liblapack-dev
         - libsuitesparse-dev
         - gfortran
