language: python
python:
   - 2.7
   - 3.4
install:
   # this is the baseline
   - sudo apt-get install python-numpy python3-numpy
   # 1. install pyvtk from pip, since that has also python3 version there (not packaged in Ubuntu)
   #
   # 2. at some point, move all this to requirements.txt; see http://docs.travis-ci.com/user/languages/python/
   #
   # 3. pip is one from virtualenv for the active python version (2.7 or 3.4), no need to change anything :)
   - pip install pyro4 pyvtk
#before_script:
#   # see https://github.com/fabric/fabric/blob/master/.travis.yml
#   # for allowing passwordless SSH to localhost
script:
   - cd examples
   - /bin/bash doTests.sh
