language: python
python:
   - 2.7
   - 3.4
install:
   #  APT stuff is below separately
   # 
   # 1. install pyvtk from pip, since that has also python3 version there (not packaged in Ubuntu)
   # 2. at some point, move all this to requirements.txt; see http://docs.travis-ci.com/user/languages/python/
   # 3. pip is exported for active virtualenv (2.7 or 3.4), no need to change anything :)
   - pip install pyro4 pyvtk
#before_script:
#   # see https://github.com/fabric/fabric/blob/master/.travis.yml
#   # for allowing passwordless SSH to localhost
script:
   - cd mupif/examples
   - /bin/bash testExamples.sh
##
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
##
sudo: false
## maybe install NumPy from miniconda in the future: https://gist.github.com/dan-blanchard/7045057
