language: python
python:
   - 2.7
   - 3.4
install:
   #  APT stuff is below separately
   # 
   # 1. at some point, move all this to requirements.txt; see http://docs.travis-ci.com/user/languages/python/
   # 2. pip is exported for active virtualenv (2.7 or 3.4), no need to change anything :)
   # 3. numpy is pre-installed by travis implicitly
   - pip install pyro4
   - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install pyvtk; fi
   - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
       git clone https://code.google.com/r/christophelebourlot-pyvtk-py3/ pyvtk-py3
       cd pyvtk-py3
       python setup.py install
     fi
   # install mupif itself
   - python setup.py install 

#before_script:
#   # see https://github.com/fabric/fabric/blob/master/.travis.yml
#   # for allowing passwordless SSH to localhost
script:
   - cd mupif/examples
   - /bin/bash testExamples.sh
##
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
##
sudo: false
## maybe install NumPy from miniconda in the future: https://gist.github.com/dan-blanchard/7045057
